target:
   drug-central:
      type: tsv
      filename:
         - data/transformed/drug_central/nodes.tsv
         - data/transformed/drug_central/edges.tsv
   STRING:
      type: tsv
      filename:
         - data/transformed/STRING/nodes.tsv
         - data/transformed/STRING/edges.tsv
   zhou-host-proteins:
      type: tsv
      filename:
         - data/transformed/zhou_host_proteins/nodes.tsv
         - data/transformed/zhou_host_proteins/edges.tsv
   hpo:
      type: tsv
      filename:
         - data/transformed/hpo/nodes.tsv
         - data/transformed/hpo/edges.tsv

destination:
   type: tsv
   filename: merged-kg

